spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      temp:
        use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/DBsql
    username: postgres
    password: 2516
    driverClassName: org.postgresql.Driver

sortByValue: id

URL: https://api.openai.com/v1/chat/completions
API_KEY: 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
